### ISSUE TITLE
这行会导致 antd 主题被覆盖

### ISSUE THREAD

**Issue by Baoyx007** [form-render/table-render#14]
https://github.com/form-render/table-render/blob/9248ecb55b7d830dd90dd86851d6482f9a27fa22/src/index.tsx#L13

**Comment by siyi98** [comment]
可以给一下复现demo吗，我这边都是正常的

**Comment by Baoyx007** [comment]
https://ant.design/docs/react/customize-theme-cn#%E6%B2%A1%E6%9C%89%E7%94%9F%E6%95%88%EF%BC%9F

> 如果你是通过 'antd/dist/antd.css' 引入样式的，改为 antd/dist/antd.less。

**Comment by siyi98** [comment]
@Baoyx007 安装最新版本试试呢，table-render@0.8.18
