### ISSUE TITLE
有没有考虑过如何应用到使用 dva/redux 的项目中？

### ISSUE THREAD

**Issue by lovesly** [form-render/table-render#15]
比如我们现在的项目是基于 umi 这一套开发的，使用了 @umijs/plugin-dva。现在引入 table-render 会有些割裂，因为 table-render 强制使用 searchApi。是否能增加一个类似 proTable 的 datasource 属性，允许数据驱动。

**Comment by siyi98** [comment]
@lovesly 当时设计api的时候就是不让用户去感知dataSource的...你可以通过setTable去设置dataSource
