### ISSUE TITLE
可以接入typescript 项目吗

### ISSUE THREAD

**Issue by fenglshyun** [form-render/table-render#4]
typescript项目中使用出错，有ts版本的吗，或者提供一份声明文件
![image](https://user-images.githubusercontent.com/44972775/103056116-063edb80-45d7-11eb-8a97-fa56c11b7a70.png)

**Comment by siyi98** [comment]
@fenglshyun 暂时没有这个计划，你可以试试在全局声明文件里面写：
```js
declare module 'table-render'
```

**Comment by siyi98** [comment]
@fenglshyun 有什么想法的话也可以进我们的钉钉群一起讨论哈
<img src="https://user-images.githubusercontent.com/29126094/103113876-92b0d300-4697-11eb-92ea-fe897c0ac4a7.png" width=300 />
