### ISSUE TITLE
Search 中 FormRender 的布局问题

### ISSUE THREAD

**Issue by mzl980425** [form-render/table-render#7]
最后一行的元素如果是同时有 px % 为单位，会导致搜索按钮无论如何都会在下一行出现
![image](https://user-images.githubusercontent.com/22958600/103392151-74474d80-4b57-11eb-8c3e-a218b335b0ea.png)

建议直接用 flex 布局，最后一格 flex-grow: 1; min-width: fit-content; 可以自动撑开最后的空闲区域
![image](https://user-images.githubusercontent.com/22958600/103392203-a5c01900-4b57-11eb-9d6d-415e5a65dc40.png)

**Comment by mzl980425** [comment]
@FateRiddle

**Comment by siyi98** [comment]
非常好的建议
